# Generated by Django 5.1.1 on 2024-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="can_preview",
            field=models.BooleanField(
                default=False,
                help_text="if user does not  have access to this course, can they see?",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("pub", "Published"),
                    ("soon", "Coming Soon"),
                    ("draft", "Draft"),
                ],
                default="pub",
                max_length=20,
            ),
        ),
    ]
