# Generated by Django 5.1.1 on 2024-09-22 09:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_lesson_can_preview_lesson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="can_preview",
            field=models.BooleanField(
                default=False,
                help_text="if user does not have access to this course, can they see?",
            ),
        ),
    ]
