# Generated by Django 5.1.1 on 2024-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_timestamp_course_updated_lesson_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order", "-updated"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
