# Generated by Django 5.1.1 on 2024-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_lesson_options_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="public_id",
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
